POST http://localhost/api/auth/register HTTP/1.1
content-type: application/json

{
    "name":"captain345",
    "firstname":"Enforcer",
    "middlename":"Chief",
    "lastname":"King",
    "picture_url":"www.myimage.com",
    "email":"captain2000@email.com",
    "password":"captain204",
    "password_confirmation":"captain204"
}
